<#
.SYNOPSIS
    Regenerate the per-device launcher-icon wiring in monkey.jungle.

.DESCRIPTION
    Every Garmin device declares its own launcher icon size. Ship one size for
    all of them and the export build warns once per mismatched device, and the
    compiler rescales the art behind your back.

    The artwork stays in a single file (resources\drawables\launcher_icon.svg).
    Devices whose launcher size differs from that file's intrinsic size get a
    resources-icon<size>\drawables\drawables.xml override that points back at
    the same SVG and sets scaleX/scaleY, plus a resourcePath line in
    monkey.jungle. This script reads the product list out of manifest.xml, looks
    up launcherIcon.width in each device's SDK compiler.json, and rewrites both.

    Run it after adding or removing an <iq:product> in manifest.xml.

.EXAMPLE
    .\tools\Sync-IconTargets.ps1
.EXAMPLE
    .\tools\Sync-IconTargets.ps1 -WhatIf     # report what would change, write nothing
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    # Intrinsic width/height of resources\drawables\launcher_icon.svg. Devices at
    # this size use the base resources\ path with no override.
    [int] $BaseSize = 40
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Everything this script reads or writes belongs to the Connect IQ project, so
# it works entirely inside watch\ - including the stale-override sweep below,
# which would silently stop pruning if it were pointed at the repo root.
$RepoRoot    = Split-Path -Parent $PSScriptRoot
$AppRoot     = Join-Path $RepoRoot 'watch'
$Manifest    = Join-Path $AppRoot 'manifest.xml'
$Jungle      = Join-Path $AppRoot 'monkey.jungle'
$BaseSvg     = Join-Path $AppRoot 'resources\drawables\launcher_icon.svg'
$DeviceRoot  = Join-Path $env:APPDATA 'Garmin\ConnectIQ\Devices'

function Write-Step ($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok   ($msg) { Write-Host "    $msg" -ForegroundColor Green }
function Write-Warn ($msg) { Write-Host "    $msg" -ForegroundColor Yellow }

# --- sanity: the base SVG really is $BaseSize, or every "40px" device warns ---

$svgHead = (Get-Content $BaseSvg -TotalCount 1)
if ($svgHead -notmatch 'width="(\d+)"' -or [int]$Matches[1] -ne $BaseSize) {
    throw ("$BaseSvg does not declare width=`"$BaseSize`". Either fix the SVG or " +
           "pass -BaseSize to match it; otherwise the devices that skip the override will warn.")
}

# --- product list -> launcher size -------------------------------------------

Write-Step "Reading products from manifest.xml"
$products = @(([xml](Get-Content $Manifest -Raw)).manifest.application.products.product |
              ForEach-Object { $_.id } | Sort-Object -Unique)
Write-Ok "$($products.Count) products"

$sizeOf = @{}
foreach ($p in $products) {
    $cfg = Join-Path $DeviceRoot "$p\compiler.json"
    if (-not (Test-Path $cfg)) {
        # A device you have not downloaded in the SDK Manager cannot be sized, and
        # guessing would silently ship the wrong icon.
        throw "No SDK device definition for '$p' ($cfg). Install it via the Connect IQ SDK Manager and re-run."
    }
    $json = Get-Content $cfg -Raw | ConvertFrom-Json
    $w = [int] $json.launcherIcon.width
    if ($w -le 0) { throw "compiler.json for '$p' has no launcherIcon.width." }
    $sizeOf[$p] = $w
}

$sizes = $sizeOf.Values | Sort-Object -Unique
Write-Ok ("launcher sizes in use: " + ($sizes -join ', '))

# --- one override folder per non-base size -----------------------------------

Write-Step 'Writing resources-icon<size> overrides'

# Drop folders for sizes no longer used, so removing a product does not leave
# an orphan resource path behind.
foreach ($stale in Get-ChildItem $AppRoot -Directory -Filter 'resources-icon*') {
    $n = [int] ($stale.Name -replace '\D', '')
    if ($sizes -notcontains $n -or $n -eq $BaseSize) {
        if ($PSCmdlet.ShouldProcess($stale.FullName, 'Remove unused icon override')) {
            Remove-Item $stale.FullName -Recurse -Force
            Write-Warn "removed unused $($stale.Name)"
        }
    }
}

foreach ($sz in $sizes) {
    if ($sz -eq $BaseSize) { continue }
    $dir = Join-Path $AppRoot "resources-icon$sz\drawables"
    $xml = @"
<drawables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://developer.garmin.com/downloads/connect-iq/resources.xsd">
    <!-- Overrides the base LauncherIcon for devices with a ${sz}x${sz} launcher.
         Same artwork as resources/drawables/launcher_icon.svg, rasterised at this
         device's launcher size. Do not copy the SVG in here - one art file only.
         Generated by tools/Sync-IconTargets.ps1. -->
    <bitmap id="LauncherIcon" filename="../../resources/drawables/launcher_icon.svg" dithering="none" scaleX="$sz" scaleY="$sz" />
</drawables>
"@
    if ($PSCmdlet.ShouldProcess("resources-icon$sz", 'Write drawables.xml')) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
        Set-Content -LiteralPath (Join-Path $dir 'drawables.xml') -Value $xml -Encoding utf8
        # @() matters: a size used by exactly one device returns a scalar, not an array.
        $n = @($sizeOf.GetEnumerator() | Where-Object { $_.Value -eq $sz }).Count
        Write-Ok "resources-icon$sz  ($n devices)"
    }
}

# --- rewrite monkey.jungle ---------------------------------------------------

Write-Step 'Rewriting monkey.jungle'

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('project.manifest = manifest.xml')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('# Per-device launcher icons.')
[void]$sb.AppendLine('#')
[void]$sb.AppendLine('# The artwork lives in exactly one place - resources/drawables/launcher_icon.svg,')
[void]$sb.AppendLine("# whose intrinsic size is ${BaseSize}x${BaseSize}. Devices whose launcher is a different size")
[void]$sb.AppendLine('# pick up a resources-icon<size>/ override that points at that same SVG and sets')
[void]$sb.AppendLine('# scaleX/scaleY, so the icon is rasterised at the device''s launcher size instead')
[void]$sb.AppendLine('# of being scaled by the compiler (which warns on every build).')
[void]$sb.AppendLine('#')
[void]$sb.AppendLine('# The launcher size is not something to guess: it is launcherIcon.width in')
[void]$sb.AppendLine('# %APPDATA%\Garmin\ConnectIQ\Devices\<id>\compiler.json. This block is GENERATED -')
[void]$sb.AppendLine('# after adding or removing an <iq:product>, run tools\Sync-IconTargets.ps1 rather')
[void]$sb.AppendLine('# than editing it by hand, or the export build starts warning again.')

foreach ($sz in $sizes) {
    if ($sz -eq $BaseSize) { continue }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("# ${sz}x${sz}")
    foreach ($p in ($sizeOf.GetEnumerator() | Where-Object { $_.Value -eq $sz } |
                    ForEach-Object { $_.Key } | Sort-Object)) {
        [void]$sb.AppendLine("$p.resourcePath = `$($p.resourcePath);resources-icon$sz")
    }
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine("# ${BaseSize}x${BaseSize} devices use the base resources/ path unchanged:")
foreach ($p in ($sizeOf.GetEnumerator() | Where-Object { $_.Value -eq $BaseSize } |
                ForEach-Object { $_.Key } | Sort-Object)) {
    [void]$sb.AppendLine("#   $p")
}

if ($PSCmdlet.ShouldProcess($Jungle, 'Rewrite')) {
    Set-Content -LiteralPath $Jungle -Value $sb.ToString().TrimEnd() -Encoding utf8
    Write-Ok "monkey.jungle rewritten ($($products.Count) products)"
}

Write-Host ''
Write-Host 'Verify with an export build, which compiles every product:' -ForegroundColor Cyan
Write-Host '  $SDK = (Get-Content "$env:APPDATA\Garmin\ConnectIQ\current-sdk.cfg" -Raw).Trim() + "bin"' -ForegroundColor DarkGray
Write-Host '  & "$SDK\monkeyc.bat" -e -o watch\bin\GarminPocketCasts.iq -f watch\monkey.jungle -y $KEY -w -l 3' -ForegroundColor DarkGray
